"""

Revision ID: 7aac1fbd4f64
Revises: 3d541307f7c7
Create Date: 2021-12-24 14:05:44.556992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7aac1fbd4f64'
down_revision = '3d541307f7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('co_2', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('t_voc', sa.Integer(), nullable=True))
    op.drop_column('data', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_column('data', 't_voc')
    op.drop_column('data', 'co_2')
    # ### end Alembic commands ###
