"""

Revision ID: ed238269290d
Revises: 7aac1fbd4f64
Create Date: 2021-12-24 14:13:30.744163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed238269290d'
down_revision = '7aac1fbd4f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'time')
    # ### end Alembic commands ###
