version: "3"
services:
  python:
    build: ./app
    container_name: app
    command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - 5000:5000
    links:
      - db
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
  nginx:
    build: ./nginx
    container_name: nginx-flask
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
